# basic options
title: Welcome to my page
description: About projects and some kind of blog
author:
  name: atecon
  #author: atecon
  #email: dbyll@ismaildemirbilek.com
  avatar: https://avatars2.githubusercontent.com/u/42611512?s=460&u=190e861586e4a701f33e755f51ec2b624d1788c1&v=4
  github: atecon
  twitter: atecon1
  bio: Economist, Data Scientist and developer
  #email_md5: 726351295ec82e145928582f595aa3aa
#twitter_username: atecon1
#github_username: atecon
# url: "https://github.com/atecon/atecon.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
# theme: jekyll-theme-dbyll
theme: jekyll-theme-minimal

# Includes an icon in the footer for each user name you enter
footer-links:
  github: atecon
  twitter: atecon1

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
